### PR TITLE
Use domain library in templates

### PR DESCRIPTION
**Pull request by stefanerwinmayer**

### CODE REVIEW

**Comment by filosganga** [comment]
It not needed

**Comment by stefanerwinmayer** [comment]
How is it not needed?

**Comment by stefanerwinmayer** [comment]
> How is it not needed?

@filosganga

**Comment by filosganga** [comment]
@stefanerwinmayer because it does not even depend on comms-audit-domain and also this library it only used by template-manager (and should not). This library is supposed to die and be rewritten.

**Comment by stefanerwinmayer** [comment]
I need to update this as otherwise I'm getting conflicts in quite a few other projects that depend on comms-template, e.g. delivery

**Pull request merged**
